version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=testing-from-prod #arg is use to send arg from docker-compose to docker build file
    ports:
      - "8000:80"



    